# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CuteMusicPlayer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire', '~> 4.0.0'
pod 'ObjectMapper', '~> 2.0.0'
pod 'AlamofireObjectMapper', :git => 'https://github.com/tristanhimmelman/AlamofireObjectMapper', :branch => 'swift-3'
pod 'Kingfisher', '~> 3.0.1'

target 'CuteMusicPlayerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CuteMusicPlayerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
